chore: download images first

diff --git a/.github/workflows/build-image-and-run-tests.yml b/.github/workflows/build-image-and-run-tests.yml
--- a/.github/workflows/build-image-and-run-tests.yml
+++ b/.github/workflows/build-image-and-run-tests.yml
@@ -9,6 +9,51 @@ jobs:
     runs-on: ubuntu-20.04
     timeout-minutes: 20
     steps:
+      - name: Download Docker images
+        run: |
+          DOCKER_IMAGES=('public.ecr.aws/l9h3g6c6/injective-exchange:prod' 'public.ecr.aws/l9h3g6c6/injective-core:prod' 'public.ecr.aws/l9h3g6c6/injective-trading-bot:latest' 'public.ecr.aws/l9h3g6c6/injective-liquidator-bot:latest')
+          echo "Downloading all docker images required by standalone network"
+          echo "Using throttle to avoid Amazon ECR's rate limting."
+          for image in "${DOCKER_IMAGES[@]}"
+          do
+            echo "Pulling image: $image"
+            attempts=0
+            until docker pull "$image"
+            do
+              [[ attempts -eq 15 ]] && echo "Reached maximum attempts of 15!" && exit 1
+              echo "Cooling down for 10 seconds."
+              sleep 10
+              ((attempts++))
+              echo "aaaagain!"
+            done
+          done
+          echo "All images downloaded"
+      - name: Export Docker images
+        run: |
+          docker save -o /tmp/injective-exchange.tar public.ecr.aws/l9h3g6c6/injective-exchange:prod
+          docker save -o /tmp/injective-core.tar public.ecr.aws/l9h3g6c6/injective-core:prod
+          docker save -o /tmp/injective-trading-bot.tar public.ecr.aws/l9h3g6c6/injective-trading-bot:latest
+          docker save -o /tmp/injective-liquidator-bot.tar public.ecr.aws/l9h3g6c6/injective-liquidator-bot:latest
+      - name: Upload Exchange image
+        uses: actions/upload-artifact@v2
+        with:
+          name: exchange-image
+          path: /tmp/injective-exchange.tar
+      - name: Upload Core image
+        uses: actions/upload-artifact@v2
+        with:
+          name: core-image
+          path: /tmp/injective-core.tar
+      - name: Upload Trading Bot image
+        uses: actions/upload-artifact@v2
+        with:
+          name: trading-bot-image
+          path: /tmp/injective-trading-bot.tar
+      - name: Upload Liquidator Bot image
+        uses: actions/upload-artifact@v2
+        with:
+          name: liquidator-bot-image
+          path: /tmp/injective-liquidator-bot.tar
       - name: Get branch name
         id: git-branch-name
         uses: EthanSK/git-branch-name-action@v1
@@ -58,51 +103,6 @@ jobs:
           name: cypress-image
           path: /tmp/cypress-image.tar
           retention-days: 1
-      - name: Download Docker images
-        run: |
-          DOCKER_IMAGES=('public.ecr.aws/l9h3g6c6/injective-exchange:prod' 'public.ecr.aws/l9h3g6c6/injective-core:prod' 'public.ecr.aws/l9h3g6c6/injective-trading-bot:latest' 'public.ecr.aws/l9h3g6c6/injective-liquidator-bot:latest')
-          echo "Downloading all docker images required by standalone network"
-          echo "Using throttle to avoid Amazon ECR's rate limting."
-          for image in "${DOCKER_IMAGES[@]}"
-          do
-            echo "Pulling image: $image"
-            attempts=0
-            until docker pull "$image"
-            do
-              [[ attempts -eq 15 ]] && echo "Reached maximum attempts of 15!" && exit 1
-              echo "Cooling down for 10 seconds."
-              sleep 10
-              ((attempts++))
-              echo "aaaagain!"
-            done
-          done
-          echo "All images downloaded"
-      - name: Export Docker images
-        run: |
-          docker save -o /tmp/injective-exchange.tar public.ecr.aws/l9h3g6c6/injective-exchange:prod
-          docker save -o /tmp/injective-core.tar public.ecr.aws/l9h3g6c6/injective-core:prod
-          docker save -o /tmp/injective-trading-bot.tar public.ecr.aws/l9h3g6c6/injective-trading-bot:latest
-          docker save -o /tmp/injective-liquidator-bot.tar public.ecr.aws/l9h3g6c6/injective-liquidator-bot:latest
-      - name: Upload Exchange image
-        uses: actions/upload-artifact@v2
-        with:
-          name: exchange-image
-          path: /tmp/injective-exchange.tar
-      - name: Upload Core image
-        uses: actions/upload-artifact@v2
-        with:
-          name: core-image
-          path: /tmp/injective-core.tar
-      - name: Upload Trading Bot image
-        uses: actions/upload-artifact@v2
-        with:
-          name: trading-bot-image
-          path: /tmp/injective-trading-bot.tar
-      - name: Upload Liquidator Bot image
-        uses: actions/upload-artifact@v2
-        with:
-          name: liquidator-bot-image
-          path: /tmp/injective-liquidator-bot.tar
   run_cypress_tests:
     name: 'Run Cypress intergration tests'
     runs-on: ubuntu-20.04
